server:
  port: 9011
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: server1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
ribbon-server: 
  name: service-ribbon
  offpath: /activemq/sendOffline
  onpath: /activemq/sendOffline
amq-server:
  name: amq-server
  offpath: /activemq/sendOffline
  onpath: /activemq/sendOffline